### ISSUE TITLE
Feature Request: Non-file inputs for TLS certificates and shared secret

### ISSUE THREAD

**Issue by WolfSkin0** [Nukesor/pueue-lib#10]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a custom remote client for pueue, but I'm running into the issue that I don't want to have to distribute the certificate or shared key as a file beside, if at all inside, the binary itself as I would like to be able to pull in those values at runtime and handle them purely in memory.

**Describe the solution you'd like**
Implementation of String/similar inputs for certificates and the shared secret so that they can be specified programmatically as Strings or buffers or other, meaning that it should be possible to deal with inconsistencies in underlying platforms and without the security implications of having to distribute the shared secret and certificates as files to those who need access.

**Describe alternatives you've considered**
- SSH: Not an option for our environment unfortunately
- Creating the relevent files at runtime: Since it's supposed to be a self-contained program, ideally I would strongly prefer minimising direct fs interaction

**Additional context**
None

---
I'd be more than happy to take a shot at developing the feature myself, and I have a few ideas of how it could be made feasible with minimal disruption to the library's existing API.

**Comment by Nukesor** [comment]
First of all, sorry for taking so long. The last months were quite busy.

I see how this can be useful when building your own tools :).
However, I also see how this can be tricky to achieve without disturbing the API too much, as the configuration, certificate handling and socket handling are super intertwined.

I would be ok with a few breaking changes, as there already are some breaking changes lined up for the next version.
The `pueue` project would of course have to be adjusted as well.

I guess the cleanest way would be to refactor this whole part into several parts.

- Get certificates from blob
- Get certificates by path via `Settings`
- Create listener/connectors from certs + `Settings`

**Comment by Nukesor** [comment]
Before you continue exploring this issue.
I'm in the process of moving the whole tls logic to rustls v0.20, while migrating to tokio and tokio_rustls at the same time.

Once this is finished and merged, you can go back to tinkering :)

**Comment by Nukesor** [comment]
Closed in favor of https://github.com/Nukesor/pueue/issues/276
